### ISSUE TITLE
I like your plugin very much, I hope he can add a function of creating playlists

### ISSUE THREAD

**Issue by turning2023** [tommy-russoniello/spotify-artist-chart#1]
I like your plugin very much, I hope he can add a function of creating playlists, because a small function can simultaneously delete duplicate tracks and rank according to popularity. It would be better if the duplicate tracks that were deleted were the complication album, my personal quirk, I hate the cover of the compilation album, and prefer the cover of the single album.

**Comment by tommy-russoniello** [comment]
Hi, glad you're finding it useful :)

Yeah, the de-duplication could be better for sure. I have a few ideas but it will be hard to get perfect since there are so many variations of names. I can definitely make it better though.

For the playlists though, do you just mean something like a button to make a playlist of all the songs in the displayed order?

**Comment by tommy-russoniello** [comment]
Well it's been a while, but I finally found some time to work on this. I've just pushed 1cc1e38 which vastly improves the track deduping as well as the names that get displayed for tracks and releases. Very few duplicates slip through at this point, and when there are duplicates, the track that gets shown is chosen much smarter.  For example, this is how the page for the Rolling Stones looked before (tons of duplicates and version metadata):
<img width="1422" alt="Screen Shot 2023-06-19 at 9 23 31 PM" src="https://github.com/tommy-russoniello/spotify-artist-chart/assets/17373311/1ea810cb-307c-457f-963e-dff18fc81b33">
And now it looks like this:
<img width="1389" alt="Screen Shot 2023-06-19 at 9 23 44 PM" src="https://github.com/tommy-russoniello/spotify-artist-chart/assets/17373311/dec500ff-5dfc-446d-8c09-8f9917facb29">
It's a really big step up in quality so I hope it solves your issues :) Feel free to re-open this issue or make a new one if you still have problems.

**Comment by tommy-russoniello** [comment]
Also, just fyi this won't actually show up in the extension from the chrome web store until my update has been approved by Google, which might not be for a few weeks.
